# Both themes can be fulfilled by this plugin. The main theme is 'What random events can occur in Minecraft?'
# However the secondary theme can be activated by setting mode to SECONDARY.

mode: PRIMARY