author: ${project.authors}
main: ${project.main}
version: ${version}
name: ${project.name}
description: ${project.description}

commands:
  event:
    description: Force a random event to happen.
    permission: ${project.name}.*
    aliases: [forceevent]

permissions:
  ${project.name}.*:
    description: Permission to use ${project.name} events.
    default: op